version: "3.9"

services:
  mongo2:
    hostname: "mongo2"
    container_name: "mongo2"
    image: "mongo:4.4-bionic"
    extra_hosts:
      - "mongo1:${MONGO1_ADDR}"
      - "mongo2:${MONGO2_ADDR}"
      - "mongo3:${MONGO3_ADDR}"
    command:
      [
        "-f",
        "/etc/mongod.conf",
        "--keyFile",
        "/auth/file.key",
        "--replSet",
        "${MONGO_REPLICA_SET_NAME}",
        "--bind_ip_all",
        "--port",
        "30002",
      ]
    restart: "on-failure"
    expose:
      - 30002
    ports:
      - 30002:30002
    volumes:
      - ./data/mongo2:/data/db
      # - ./logs/mongo2:/var/log/mongodb
      - ./config/mongod.conf:/etc/mongod.conf
      - ./auth/file.key:/auth/file.key
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "500m"
